import type { Trip, Vehicle, TripSummary, Organization, SubOrganization } from "./types";
import type { EmployeeGroup } from "./admin";
import { buildVehicleExportSnapshot } from "./vehicles";

const now = Date.now();
const ms = (d: number, h: number, m: number) =>
  new Date(new Date().getFullYear(), new Date().getMonth(), d, h, m).getTime();

// ─── Fiktivní cesty zaměstnance ───────────────────────────────────────────────

export const DEMO_RECENT_TRIPS: Trip[] = [
  {
    id: "demo-t1",
    userId: "demo-user",
    vehicleId: "demo-v1",
    transportMode: "car",
    purpose: "Školení zaměstnanců – Brno",
    startTime: null,
    startTimeMs: ms(10, 7, 30),
    endTime: null,
    startLocation: null,
    endLocation: null,
    distanceKm: 142,
    distanceSource: "gps_route",
    ticketPrice: null,
    kmRatePerKm: 5.8,
    kmCost: 824,
    perDiemHours: 10,
    perDiemAmount: 225,
    status: "approved",
    notes: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "demo-t2",
    userId: "demo-user",
    vehicleId: null,
    transportMode: "train",
    purpose: "Porada vedení – Praha",
    startTime: null,
    startTimeMs: ms(5, 8, 15),
    endTime: null,
    startLocation: null,
    endLocation: null,
    distanceKm: null,
    distanceSource: "ticket",
    ticketPrice: 340,
    kmRatePerKm: null,
    kmCost: null,
    perDiemHours: 14,
    perDiemAmount: 225,
    status: "draft",
    notes: null,
    createdAt: null,
    updatedAt: null,
  },
  {
    id: "demo-t3",
    userId: "demo-user",
    vehicleId: "demo-v1",
    transportMode: "car",
    purpose: "Návštěva klienta – Olomouc",
    startTime: null,
    startTimeMs: ms(2, 9, 0),
    endTime: null,
    startLocation: null,
    endLocation: null,
    distanceKm: 28,
    distanceSource: "gps_route",
    ticketPrice: null,
    kmRatePerKm: 5.8,
    kmCost: 162,
    perDiemHours: 6,
    perDiemAmount: 148,
    status: "approved",
    notes: null,
    createdAt: null,
    updatedAt: null,
  },
];

// ─── Fiktivní vozidlo ───────────────────────────────────────────────────────

export const DEMO_VEHICLE: Vehicle = {
  id: "demo-v1",
  userId: "demo-user",
  vehicleName: "Škoda Octavia Combi 1.6 TDI",
  plateNumber: "1AB 2345",
  engineVolumeCcm: 1598,
  fuelType: "diesel",
  consumption1: 5.2,
  consumption2: 4.1,
  consumption3: 4.5,
  insurancePolicyNumber: "123-456-789",
  insuranceValidUntil: "2026-12-31",
  stkValidUntil: "2026-06-30",
  kmRatePerKm: 5.8,
  isActive: true,
  createdAt: null,
  updatedAt: null,
};

// ─── Probíhající cesta (pro stav "traveling") ─────────────────────────────────

export const DEMO_ACTIVE_TRIP: Trip = {
  id: "demo-active",
  userId: "demo-user",
  vehicleId: "demo-v1",
  transportMode: "car",
  purpose: "Terénní práce – Zlín",
  startTime: null,
  startTimeMs: now - 45 * 60 * 1000, // před 45 min
  endTime: null,
  startLocation: null,
  endLocation: null,
  distanceKm: null,
  distanceSource: "gps_route",
  ticketPrice: null,
  kmRatePerKm: 5.8,
  kmCost: null,
  perDiemHours: 0,
  perDiemAmount: null,
  status: "active",
  notes: null,
  createdAt: null,
  updatedAt: null,
};

// ─── Souhrn cesty (po dokončení) ──────────────────────────────────────────────

export const DEMO_TRIP_SUMMARY: TripSummary = {
  distanceKm: 87,
  kmCost: 505,
  perDiemHours: 8,
  perDiemAmount: 148,
  transportMode: "car",
  ticketPrice: null,
};

// ─── Admin view – skupiny zaměstnanců s cestami ──────────────────────────────

export const DEMO_GROUPS: EmployeeGroup[] = [
  {
    uid: "u1",
    displayName: "Jan Novák",
    email: "jan.novak@euroinstitut.cz",
    organization: "euroinstitut" as Organization,
    subOrganization: "OLK" as SubOrganization,
    homeAddress: "Olomoucká 15, 779 00 Olomouc",
    birthDate: "1985-06-15",
    personalNumber: "Z0123",
    phone: "+420 777 000 111",
    bankAccount: "123456789/0100",
    variableSymbol: "9926031901",
    insuranceCompany: "Kooperativa",
    travelOrderInMonth: "1",
    payoutDueDate: "2026-04-15",
    exportVehicle: buildVehicleExportSnapshot(DEMO_VEHICLE),
    trips: [
      {
        id: "t1",
        userId: "u1",
        vehicleId: "v1",
        transportMode: "car",
        purpose: "Školení zaměstnanců – Brno",
        startTime: null,
        startTimeMs: ms(10, 7, 30),
        endTime: null,
        startLocation: null,
        endLocation: null,
        distanceKm: 142,
        distanceSource: "gps_route",
        ticketPrice: null,
        kmRatePerKm: 5.8,
        kmCost: 824,
        perDiemHours: 10,
        perDiemAmount: 225,
        status: "approved",
        notes: null,
        createdAt: null,
        updatedAt: null,
      },
      {
        id: "t2",
        userId: "u1",
        vehicleId: null,
        transportMode: "train",
        purpose: "Porada vedení – Praha",
        startTime: null,
        startTimeMs: ms(5, 8, 15),
        endTime: null,
        startLocation: null,
        endLocation: null,
        distanceKm: null,
        distanceSource: "ticket",
        ticketPrice: 340,
        kmRatePerKm: null,
        kmCost: null,
        perDiemHours: 14,
        perDiemAmount: 225,
        status: "draft",
        notes: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    totalKm: 142,
    totalKmCost: 824,
    totalPerDiem: 450,
    totalTickets: 340,
    totalAll: 1614,
  },
  {
    uid: "u2",
    displayName: "Marie Svobodová",
    email: "marie.svobodova@euroinstitut.cz",
    organization: "euroinstitut" as Organization,
    subOrganization: "PHA" as SubOrganization,
    homeAddress: "U hranic 12, 100 00 Praha 10",
    birthDate: "1990-03-22",
    personalNumber: "Z0456",
    phone: "+420 603 222 333",
    trips: [
      {
        id: "t3",
        userId: "u2",
        vehicleId: "v2",
        transportMode: "car",
        purpose: "Návštěva SPC – Praha 4",
        startTime: null,
        startTimeMs: ms(12, 8, 0),
        endTime: null,
        startLocation: null,
        endLocation: null,
        distanceKm: 45,
        distanceSource: "gps_route",
        ticketPrice: null,
        kmRatePerKm: 5.8,
        kmCost: 261,
        perDiemHours: 7,
        perDiemAmount: 148,
        status: "approved",
        notes: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    totalKm: 45,
    totalKmCost: 261,
    totalPerDiem: 148,
    totalTickets: 0,
    totalAll: 409,
  },
  {
    uid: "u3",
    displayName: "Petr Dvořák",
    email: "petr.dvorak@eduservis.cz",
    organization: "eduservis" as Organization,
    subOrganization: null,
    trips: [
      {
        id: "t4",
        userId: "u3",
        vehicleId: "v3",
        transportMode: "car",
        purpose: "Školení – Ostrava",
        startTime: null,
        startTimeMs: ms(8, 6, 45),
        endTime: null,
        startLocation: null,
        endLocation: null,
        distanceKm: 312,
        distanceSource: "gps_route",
        ticketPrice: null,
        kmRatePerKm: 6.2,
        kmCost: 1934,
        perDiemHours: 16,
        perDiemAmount: 353,
        status: "approved",
        notes: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    totalKm: 312,
    totalKmCost: 1934,
    totalPerDiem: 353,
    totalTickets: 0,
    totalAll: 2287,
  },
  {
    uid: "u4",
    displayName: "Eva Nováková",
    email: "eva.novakova@biotherapy.cz",
    organization: "biotherapy" as Organization,
    subOrganization: null,
    trips: [
      {
        id: "t5",
        userId: "u4",
        vehicleId: null,
        transportMode: "train",
        purpose: "Konference – Brno",
        startTime: null,
        startTimeMs: ms(15, 7, 0),
        endTime: null,
        startLocation: null,
        endLocation: null,
        distanceKm: null,
        distanceSource: "ticket",
        ticketPrice: 420,
        kmRatePerKm: null,
        kmCost: null,
        perDiemHours: 12,
        perDiemAmount: 225,
        status: "draft",
        notes: null,
        createdAt: null,
        updatedAt: null,
      },
    ],
    totalKm: 0,
    totalKmCost: 0,
    totalPerDiem: 225,
    totalTickets: 420,
    totalAll: 645,
  },
];
